### PR TITLE
[TON Actions Team] #12 Contest: TON OS Startup Edition installation scripts [Part 2 | Integration with TONDEV CLI]

### PR DESCRIPTION
**Pull request by ch1seL**

### CODE REVIEW

**Review by nrukavkov — APPROVED** [review]

**Comment by Artem-Zhdanov** [comment]
Some commands work in unexpected ways:
 -  in a new repository, the `se-nd info` command starts the tar.gz download (why), instead of just saying that `tonos-se` is not installed 
-  `se-nd reset` does not clean up the database as expected (bug)

The directory structure is very convenient, but it would be nice to put it inside the .tondev folder

**Comment by papanomad535** [comment]
- some install issues on Windows: needed to change default npm version to unspecified v6 (current pkg nodejs v14.17.5 goes with npm v.7.21.10 by default) and reinstall npm globally, 
- required sudo privileges on macOS/linux.

**Comment by Artem-Zhdanov** [comment]
> * required sudo privileges on macOS/linux.

@papanomad535  are you sure? When it runs (which is by default) on unprivileged port it doesn't

**Comment by papanomad535** [comment]
> > * required sudo privileges on macOS/linux.
> 
> @papanomad535 are you sure? When it runs (which is by default) on unprivileged port it doesn't

I meant the installation/npm, yes it was necessary. Not necessary to run on sudo, sorry if I was unclear

**Comment by nrukavkov** [comment]
> > > * required sudo privileges on macOS/linux.
> > 
> > 
> > @papanomad535 are you sure? When it runs (which is by default) on unprivileged port it doesn't
> 
> I meant the installation/npm, yes it was necessary. Not necessary to run on sudo, sorry if I was unclear

There is no need a sudo if you change default folder for installing global packages https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by nrukavkov** [comment]
> * some install issues on Windows: needed to change default npm version to unspecified v6 (current pkg nodejs v14.17.5 goes with npm v.7.21.10 by default) and reinstall npm globally,

We tested it and the solution works with both npm versions 6th and 7th.

**Pull request closed without merging**
